### ISSUE TITLE
SBV General Performance 

### ISSUE THREAD

**Issue by doyougnu** [LeventErkok/sbv#484] opened 2019-09-01 19:27 UTC
Hey Levent,

I finally have some time to try and improve some of the general performance characteristics of `sbv` as we briefly touched on in #460. But before investing significant time looking at the code base I was wondering if you had a benchmark suite or performance suite already made?

There is a nice list of benchmark problems [here](https://www.cs.ubc.ca/~hoos/SATLIB/benchm.html) that I could begin encoding as a first step.

Let me know what you think and feel free to close as this isn't really an "issue"

**Comment by LeventErkok** [comment] 2019-09-01 19:44
Hi Jeffrey:

No, SBV does not have any performance test-suites. It’d be great to have one indeed. If you could add one (based on criterion most likely?), that’d be an extremely valuable contribution.

One thing I'd worry about would be separating SBV performance and backend solver performance. It'd be great to keep track of them separately, so someone looking at an outlier can easily see what the origin of the problem is. For query mode problems this might be tricky to do, but the batch mode interface (i.e., regular calls to `prove`/`sat` etc.) can be easily transformed to simply produce the SMTLib problem and stop so you can keep track of performance there; and then separately measure how long the backend solver takes. There's some design space here to explore, but yeah, I'd say go for it by all means!

**Comment by doyougnu** [comment] 2019-09-17 20:04
I've forked, setup a branch for this [here](https://github.com/doyougnu/sbv/tree/sbv_benchmarking) and written an initial benchmark suite based on `criterion` following the layout/organization of your test suite. I've added benchmarks for all of the puzzle examples so please give it a look, you should be able to just run `cabal bench` per the usual. 

This turned out to be much easier than I initially thought. To assess the overhead of `sbv` where `overhead = sbv solution time - backend solver solution time` I just setup a benchmarking environment for each problem with criterion. The environment uses `sbv` to generate a `transcript` for the problem at hand and then passes the transcript to the backend solver. I've written essentially no error handling for this but it seems to work well. I did run into an issue with calls to `output`; it seems that `output` does not play nice with either `criterion` or `transcript` but I'm not sure which. 

Lastly, I've added `*.nix` files because I'm on nixOS, but I figure in the pull request I'll just delete them and squash, if that's not too much trouble. I was also thinking of trying to make a custom report template for `criterion` instead of relying on command line output. It would be nice to have `%overhead` for specific problems or classes of problems.

**Comment by LeventErkok** [comment] 2019-09-17 20:24
Thanks! How do I run this?

**Comment by doyougnu** [comment] 2019-09-17 22:08
To run the benchmarks you just need to:
  - `cd` to the directory that holds `sbv.cabal`. 
  - Enable benchmarks with either`cabal configure --enable-benchmarks` or `cabal new-configure --enable-benchmarks`
  - run `cabal bench` or `cabal new-bench`. 

 I believe this should be similar to running the test suite. 

Furthermore, the benchmarks are specified as a target in `sbv.cabal` so if you wanted to you can point a repl to it via `cabal repl bench:SBVBench` or `cabal new-repl bench:SBVBench` and get a ghci instance that loads the benchmark environment. I haven't added any dependencies other than `criterion` so please let me know if you cannot get it working.

**Comment by LeventErkok** [comment] 2019-09-17 22:55
Thanks! I'll give this a try soon.

**Comment by LeventErkok** [comment] 2019-09-18 17:38
@doyougnu Thanks for this, great work!

One question: How do we track if something went bad? With a regular test, we know if something fails. Is there a corresponding notion in benchmarking that says things have gotten faster/slower? Is that part of the framework you built, or do we need something extra to alert us about deviances?

**Comment by doyougnu** [comment] 2019-09-18 23:23
Good question. All the benchmarking suite I wrote does is provide a framework to test the overhead of `sbv`. Tracking performance over many versions (regression benchmarking? or perhaps golden benchmarks?) is something that would require extra work. But in theory I don't think this would be too hard. Each benchmark is already denoted by a string like `standalone/coins` or `sbv/nqueens 2` and writing these out to a csv file is just a matter of passing `--csv filename.csv` to the benchmark call or setting this via criterion directly. It is the easy to envision an auxiliary tool that reads in these files and does some sort of statistical process control (see [this](https://en.wikipedia.org/wiki/Statistical_process_control) and [this](https://www.itl.nist.gov/div898/handbook/pmc/section1/pmc12.htm)) to check whether a feature or fix has introduced a statistically significant change in performance. Not sure if anything like this exists though.

On an unrelated note, if what I have now looks good to you then I'll write the benchmarks for the rest of the examples in the documentation. I'd still like a better report from criterion than just the `stdout` output and I'd prefer to have a general statement of `%overhead` that would average the differences between solving  a problem in sbv vs the backend solver. It won't ever match exactly because sbv parses the output of the backend solver but it would be a nice number to have. What would be most useful to you?

**Comment by LeventErkok** [comment] 2019-09-19 01:15
Thanks, I see the use-case.

Go ahead and make a pull-request when ready. For the first round, we'll just have the "reports" generated. I really have no preference regarding what to output, whether it's overhead or not. The utility of these benchmarks is in making sure things don't get slower while SBV is working on them in my mind; regardless of how long the solver takes; so overhead may not really be that relevant. (z3 times can vary widely.) But no harm in including that data. I'll leave it up to you.

For the second phase though, we'd need some mechanism of detecting deviances. Whether that's done by a separate program or can be handled in the benchmark infrastructure itself depends on how easy either option would be. Would be nice if everything is in one place and handled automatically, but a simple program to compare old results to new wouldn't be that bad either. I'll defer to your judgment as I don't really have an informed opinion. What does GHC do for tracking it's performance?

**Comment by doyougnu** [comment] 2019-09-26 18:34
Phase 1 pull request up: https://github.com/LeventErkok/sbv/pull/489

For Phase 2 it looks like `ghc` uses a tool called `gipeda` for a performance dashboard. You can view the output of it at [https://perf.haskell.org/ghc/](https://perf.haskell.org/ghc/). It looks like it integrates with `criterion` fairly well, I also found [this](http://hackage.haskell.org/package/cloben) script that converts `criterion` output into a `gipeda` readable format.

These tools don't fulfill the vision for phase 2 though. They result in nice visualizations of performance by commit but they do not perform any automatic detection of performance anomalies. It sounds like a fun side project though so I can try to author such a tool.

What are your thoughts?

**Comment by LeventErkok** [comment] 2019-09-26 20:50
Thanks for the commit; fantastic work! Much appreciated.

I think phase-1 is valuable on its own, even without a way to "track" performance, as it establishes methodology.

To make this practical, however, we do need a way to track and tell us when things go bad. (Or unexpectedly good, I suppose.) I really have no opinion on what the best approach here is, and I will leave it to you to define what that means and see it through, as your energy/time permits. While it's definitely not urgent, I definitely think a tracking system, however rudimentary, is an essential part of this system.

**Comment by doyougnu** [comment] 2020-06-23 11:44
Hey Levent,

I stumbled upon this package: https://hackage.haskell.org/package/bench-show

It seems to fit most of our needs for tracking benchmark tests across commits. Does not look like it integrates with `tasty` to provide failed tests if a commit becomes slower. 

What are your thoughts? This could be an easy plug-and-play win.

- Jeff

**Comment by LeventErkok** [comment] 2020-06-23 14:23
Hi Jeff. Looks great! I'm all for using other people's work!

I've invited you to be a developer on sbv on github. I think that means you're allowed to directly commit, without a pull request. Happy hacking!

**Comment by doyougnu** [comment] 2020-06-23 14:46
Ok great. Thanks for the invite. If it is ok with you I would still prefer to go through the `commit to my fork` -> `squash merge` -> `PR` workflow. I just find it more hygienic and it keeps me from making completely unreadable commit logs :)

**Comment by LeventErkok** [comment] 2020-06-23 14:56
No problem; whatever is most convenient for you works for me!

**Comment by doyougnu** [comment] 2020-06-29 14:59
Hey Levent,

I have a good candidate setup using `bench-show` to compare performance over time for the benchmarks. Before I open a PR I wanted to get an idea of the continuous integration strategy and your opinion of adding a few new cabal targets. Basically lots of these benchmarks are very heavy weight, even fast benchmarks which take `~20ms` can be expensive because `gauge` and `criterion` run them ten times to generate a good sample. I think there are really two needs that need be solved here: 1) provide a target for continuous integration 2) provide a target for fine tuning to facilitate changing sbv while tracking specific functions or internals (using `bench-show`).

The current workflow is:
1. running `cabal bench` or `cabal vs-run SBVBench` will run all benchmarks outputting results to a UTC timestamped file in a sub-directory of the benchsuite, for example: `/sbv/SBVBenchSuite/BenchFiles/2020-06-27-15:54:05.447753608-UTC.csv`
2. To _not run_ all the benchmarks but only a subset, `gauge` and `criterion` allow regexes to be passed from the command line like this: `cabal build SBVBench; ./SBVBench --match=pattern -- 'NQueens'`
3. I've setup a function to wrap over the `bench-show` api so to easily generate comparisons. `bench-show` expects runs to be appended to the file it is analyzing, which creates friction between comparisons and the UTC files, so right now I change `main` in the benchmark suite to generate a filename with only a date rather than a date + time. In any case the workflow is: `cabal bench` -> `make changes` -> `cabal bench` (to the same file in `BenchFiles`) -> `cabal repl SBVBench` -> `*Utils.SBVBenchFramework> compareBenchMarksCli <filename-here>`

and here is an example output from `bench-show`:
```
*Utils.SBVBenchFramework> compareBenchMarksCli "SBVBenchSuite/BenchFiles/2020-6-27.csv"

(Mean)
Benchmark           Puzzles(0)(ms) Puzzles(1) - Puzzles(0)(%) Puzzles(2) - Puzzles(0)(%) Puzzles(3) - Puzzles(0)(%)
------------------- -------------- -------------------------- -------------------------- --------------------------
//NQueens.NQueens 5          51.52                     -50.64                     -46.29                     -55.27
```
Showing four runs of NQueens 5 (0, 1, 2, 3) and their comparisons as a percentage `(0 - 1), (0 - 2), (0 - 3)`. You'll notice that all the runs after run 0 is ~50% faster, this is because I added `INLINE` pragmas to the benchsuite which was removing noise.

So I think the CI should be split into a separate cabal target, ideally we would:

1) Select a subset of benchmarks to run with every commit and live with the additional time during CI. We would need to know what a good time limit for the benchmark would be (right now I have it set to `300s` or `5 min`), but this is likely too expensive.
2) Then just accumulate results over the course of the project life.

And additionally for fine-tuning `sbv` itself I would like to add another cabal target such that I can do `cabal v2-run BenchTarget` and get a benchmark for a specific function or part of `sbv` I'm looking to performance tune which would frequently change. I'm honestly not sure what the best practices are, we could also split this second benchmark target into another project like: `sbv-benchmarks` and link to the main `sbv` repo as a submodule or something similar to maintain good coherence.

**Comment by LeventErkok** [comment] 2020-06-29 16:17
Hi Jeff,

I think adding new targets to the cabal file is perfectly fine, and I'm perfectly happy to have as many as you need so long as it has no impact on a non-suspecting user: i.e., if someone says `cabal install sbv`, these extra targets should have no impact on what gets built on their machine. (I believe this is already the case, but just wanted to double check.)

Regarding CI: We actually no longer even run regression tests in CI. I've captured this here: https://github.com/LeventErkok/sbv/issues/479 So, expecting the "free" CI infrastructure from Travis or Circle-CI (or any other free provider) to handle these sorts of load seems unrealistic. (Unless you know of an alternative! I'd love to have regular regressions running in CI again.)

But that doesn't mean the freamework you're building for benchmarking is for naught: We'll have to do this manually and occasionally, over a cherry-picked set of benchmarks for the time being. And I'm quite interested in having this infrastructure in place, and your efforts are very much appreciated. I suggest we go with a "manual" mindset for the time being and see how things evolve over time.

**Comment by doyougnu** [comment] 2020-06-30 13:31
Hey Levent,

> (I believe this is already the case, but just wanted to double check.)

Yes this is the case and I would like to keep it this way. Tests and benchmarks should be orthogonal to the library.

> We actually no longer even run regression tests in CI.

Ah this is unfortunate, I've read through the issue and I also don't see an easy solution. Even if the CI was moved to something like `nix` and then a `release.nix` derivation was provided for `sbv` the same issues with `z3` would arise, or worse the CI would only work for the version of `z3` on `nixpkgs`.

>  We'll have to do this manually and occasionally, over a cherry-picked set of benchmarks for the time being

This is completely fine with me. I'll add the cabal targets and open a PR in the next few days. I think one thing to be aware of is the benchmarks will be sensitive to the underlying machine, and so comparing benchmarks across machines is likely to lead to nonsense. Just an extra source of error for the manual methods.

I've been reading through the source code and have some ideas on possible performance gains. Clearly the underlying solver will dominate the runtime but closing the overhead (I'll have to calculate this number) as much as possible would be best. Here are some ideas I had:

### Semantic agnostic changes
1. `String` -> `Text` 
  This is likely technical debt that needs to be collected. From my initial benchmarks over `Puzzles` something like 10-20% of runtime is traced to `show`. I think this may be because once a `show` is invoked a bunch of thunks are forced and a garbage collection call is triggered. So I think this would be a good case to use `Data.Text.Strict`, then migrate any `++` to `<>`. That is, laziness in these instances are required for something I am not familiar with.
2. Swapping out some old data structures like ` [(String, [String])]` for a more appropriate data structure, e.g., `HashMap` or `Seq`. Using `HashMap`s would add an `unordered-containers` dependency.
2. Add language pragma for `SPECIALIZE`'ing the type classes
3. Adding more  `INLINE` pragmas for functions like `cache` and `uncache`. There is also the possibility of adding `NOINLINE` pragmas for known slow code branches but this would requires more care and good evidence.

### Semantic aware changes
1. Using a `pay-it-forward` approach. Ideally any `Maybe <something>` type would be translated into a `NotEmptySomething`  type so that subsequent code can make use of the information to avoid runtime checks like `foo | 0 <= i = bar`, similar to this [blog post](https://www.parsonsmatt.org/2017/10/11/type_safety_back_and_forth.html).

The Semantic agnostic changes are pretty light weight (although are likely to have large changes per commit) in my opinion, and I'm sure there are other algorithmic changes to make but I'm just not as familiar with the code base at the moment. Any pointers or other ideas you may have would be appreciated and I think it would be good to collect them to orient future work.

Ok, I swear this is my last wall of text comment.

**Comment by LeventErkok** [comment] 2020-06-30 14:34
@doyougnu 

Sounds like a good plan moving ahead! I'm all for making semantics preserving improvements, both for performance and maintainability.

Regarding `String` to `Text` conversion: I actually tried something similar some time ago: https://github.com/LeventErkok/sbv/compare/no-string-backend I was motivated by both performance, and nicer formatting of the output. (I tried replacing `String` with `Doc`.) But that branch never got merged to master! Because I found it did pretty much no difference in speed: When you communicate over a text-pipe to another process, the IO times are so high that it absolutely dominates any strings you build. Especially given we communicate with the solver line-by-line (expecting a `success` response after each command), I trust that'll be even more true today than when I did that experiment about 4-5 years ago. (Back then, there was no query mode; so everything was sent all together at once, only "interacting" at model extraction time.)

So, I wouldn't expect any performance gains out of that, but it can still reduce memory foot-print; and that's always a good thing. If anything, creating proper types for `[(String, [String])]` (and there's plenty of them around!) helps with factoring.

I suggest doing this over many small improvements, instead of big transformations. Continuous improvement is better than large efforts (like I tried with `String -> Doc` conversion), as you can still keep the parts that improve readability. Thanks for all your contributions and looking forward to seeing more!

**Comment by LeventErkok** [comment] 2020-12-13 05:47
@doyougnu Time to close this one?

**Comment by doyougnu** [comment] 2020-12-13 18:21
@LeventErkok 

I'd like to keep this one open and close #545 to consolidate the performance work. There are still some easy wins to be had that I'd like to do:

1. remove `reverse`'s by cons'ing to the end of the sequence (this will need to be a PR because we'll have to validate the code again)

2. Get all of Core to use Text. Even if this is just a memory-footprint win then it is still a win in my book!

what do you think?

**Comment by LeventErkok** [comment] 2020-12-13 19:45
Sounds good. Would be nice to have a release somewhere before the end of the year, though there are no set deadlines. Thanks!

**Comment by LeventErkok** [comment] 2021-09-22 12:34
Closing this as I don’t think we’ll act on it for now.

**Closed by LeventErkok** 2021-09-22 12:34 UTC
Labels: Nice to have, Performance, Design exploration
