### ISSUE TITLE
yices proof fails with "Unexpected non-success response"

### ISSUE THREAD

**Issue by brianhuffman** [LeventErkok/sbv#335] opened 2017-11-06 22:30 UTC
This example below is from GaloisInc/cryptol#444. (Sorry I haven't converted it to a Haskell/SBV example.) Basically, yices fails if you send it a value raised to an exponent greater than 2^31-1, and SBV doesn't handle the failure in a nice way.
```
Cryptol> :set prover=yices
Cryptol> :prove \(x:[32]) -> x!0 ==> x * (x ^^ -1) == 1

SBV error:

*** Data.SBV: Unexpected non-success response from Yices:
***
***    Sent      : (define-fun s64 () (_ BitVec 32) (bvmul s63 s63))
***    Expected  : success
***    Received  : (error "at line 71, column 35: in bvmul: maximal polynomial degree exceeded")
***    Exit code : ExitSuccess
***
***    Executable: /Users/huffman/.bin/yices-smt2
***    Options   : --incremental
***
*** Failed to establish solver context. Running in debug mode might provide
*** more information. Please report this as an issue!
```

**Comment by LeventErkok** [comment] 2017-11-07 00:32
It feels to me like SBV is handling the failure in quite a nice way actually :-)

What would you have SBV do in this case? I'm not sure how to recover from something like this.

**Comment by brianhuffman** [comment] 2017-11-07 00:50
I wouldn't call it "nice": it calls the Haskell `error` function with a message that says "Please report this as an issue!"

It would be nicer if instead of calling `error`, it returned an `Unknown` response, like it does with z3:
```
Cryptol> :set prover=z3
Cryptol> :prove \(x:[26]) -> x!0 ==> x * (x ^^ -1) == 1
Unknown.
  Reason: Overflow encountered when expanding vector
(Total Elapsed Time: 34.737s, using Z3)
```

**Comment by LeventErkok** [comment] 2017-11-07 00:57
I see. Currently, SBV will say "Unknown" if it gets to issue "check-sat" and the solver actually does return an unknown result. This seems safe.

When the solver actually returns `error` in response to anything we send (regardless whether it's a check-sat or not), then we throw an exception. Because we really don't know what happened. For instance, SBV can be sending down complete garbage; and we would like to know that.

This is what's happening here. Z3 is nice enough to wait and tell you `unknown`; but yices is eager and simply chokes. I don't think either behavior is wrong, though obviously they are different.

It seems only way to distinguish would be to actually read the "error" message sent back and do some analysis on whether it can be turned into "unknown". But that seems fragile at best, and really not in the spirit of the interface. If we get an error, then it's something to worry about.

I'm not sure how else to proceed here; if we start assigning semantics to error messages from individual solvers, that'll likely lead to a whole can of worms down the road.

**Comment by brianhuffman** [comment] 2017-11-07 01:14
Ok, I see now that we shouldn't conflate "error" and "unknown" responses; they mean different things.

But I would really prefer the error response to be handled by some means other than the Haskell `error` function. I see that the `SMTResult` datatype actually has a `ProofError` constructor; why don't you use that?

With `error`, I have to install an exception handler in the `IO` monad to catch it, and it's hard to be sure I won't accidentally catch panics or other uses of `error` that come from different sources.

**Comment by LeventErkok** [comment] 2017-11-07 02:09
That is a good point; we should be able to make better use of `ProofError`.

Can you create a direct test case in SBV to exhibit this behavior? I'll see what I can do!

**Comment by LeventErkok** [comment] 2017-11-07 21:22
Perhaps a compromise would be to throw a specific exception if we get an "error" back from the solver, instead of calling `error`. Something like `SMTSolverError` or some such. That way Cryptol can catch that particular exception and ignore others to percolate. Would that serve the purpose?

**Comment by brianhuffman** [comment] 2017-11-08 01:16
If you can't put the error in the `ProofError` constructor, then you should define an exception type and use `throwIO` from `Control.Exception`. This would make it easy to write a handler that catches all SBV exceptions and nothing else. Also, as the documentation for Control.Exception states: "The `throwIO` variant should be used in preference to `throw` to raise an exception within the IO monad because it guarantees ordering with respect to other IO operations, whereas throw does not." (afaik `error s` is basically `throw (ErrorCall s)`)

**Comment by LeventErkok** [comment] 2017-11-22 01:33
@brianhuffman I was just looking at this again, and I'm actually getting a segmentation-fault from Z3 with this query. (My Z3 version is quite fresh.) I'm guessing you must be using a rather old version of Z3? Perhaps that should be reported to the Z3 folks separately.

**Comment by brianhuffman** [comment] 2017-11-22 17:55
I'm using z3 version 4.5.0, which I understand is the latest release.

**Comment by LeventErkok** [comment] 2017-11-22 19:49
Indeed 4.5.0 is the latest "release," but their github master is a good 1869 commits ahead from that: https://github.com/Z3Prover/z3/releases/tag/z3-4.5.0

I'll report this as a regression for them.

**Comment by LeventErkok** [comment] 2017-11-22 19:53
@brianhuffman Interesting. By looking at the generated SMT-Lib, this one seems to be using 26-bits only. (Not 32 as in the original.)

What happens if you try with 32-bits?

**Comment by brianhuffman** [comment] 2017-11-22 22:16
26 bits is the smallest size at which z3 fails, and it is the same size I used in my original z3 example.

I just tried z3 with 32 bits; in Cryptol I get
```
Cryptol> :prove \(x:[32]) -> x!0 ==> x * (x ^^ -1) == 1

SBV error:

*** Error     : fd:15: hGetLine: end of file
*** Executable: /Users/huffman/.bin/z3
*** Options   : -nw -in -smt2
*** Request   : (check-sat)
***
*** Giving up!
```
Up to size 28 I get an "unknown" response just like with size 26, but with 29 and above I get the "Giving up!" response (which I guess signifies a segfault).

**Comment by LeventErkok** [comment] 2017-11-23 05:53
That makes sense. The `fd:15: hGetLine: end of file` is the tell-tale sign of seg-fault: The pipe disappears when the solver crashes.

**Comment by LeventErkok** [comment] 2017-11-25 07:39
@brianhuffman Finally got around to implementing this. SBV will now `throwIO` if the solver ever responds with `error`. It'll throw `SMTException`, defined thusly: https://github.com/LeventErkok/sbv/blob/190fa05314a4f1ac067695db9094845f5f4d1511/Data/SBV/SMT/Utils.hs#L135-L146

There's a nice `Show` instance for this type; so if you `catch \(e :: SMTException)` and display the `show`'d value to the user it would provide enough info. Then you can go back to the Crytol REPL. Of course, if you want to inspect the fields of this data type and take further action, that's possible too. Note that if you ever catch this exception, the solver is no longer alive at that point; i.e., `Query` mode users would have lost the access to the pipe at that point. I guess that part doesn't really matter for Cryptol.

Exceptions are tricky to deal with, so I'll keep this ticket open and refrain from making a release till you get a chance to test this out and make sure it works as expected. Let me know what you find out!

**Comment by LeventErkok** [comment] 2017-12-14 19:51
@brianhuffman Did you get a chance to test this out? Would like to close the ticket if we have some confirmation that it works as expected.

**Comment by LeventErkok** [comment] 2018-01-04 18:35
@brianhuffman I'm intending to make a new SBV release in about a week or so. I don't know if you got a chance to test this out. Would like to close this ticket before the release.

**Comment by LeventErkok** [comment] 2018-01-13 18:00
SBV 7.5 will be released soon; I'm closing this ticket as I think this release addresses it. If not, please feel free to reopen!

**Closed by LeventErkok** 2018-01-13 18:00 UTC
Labels: Improvement
