### ISSUE TITLE
SBV gives incomplete results on `allSat`

### ISSUE THREAD

**Issue by TomMD** [LeventErkok/sbv#201] opened 2015-12-08 21:35 UTC
As seen on StackOverflow (http://stackoverflow.com/questions/34162834/why-does-this-sbv-code-stop-before-hitting-the-limit-i-set) SBV is giving only some of the satisfying models when allsat is used.  Suspiciously, the last model is an empty list:

    [[9,27,6],[64,512,24],[]]

Some tests with older versions of SBV (4.2) shows Z3 is throwing an exception at this point.  Is the empty list a symptom of an exceptional condition from the solver?  If so, should an alternative solution be decided on or the empty list be a hackish but documented solution to this case?

**Comment by LeventErkok** [comment] 2015-12-08 23:13
@TomMD This is a mere consequence of the fact that the problem is non-linear and Z3 gives up after the "constraints" become too hard. What "hard" means is truly heuristic, different versions of Z3 can produce different results. I wrote up a detailed answer for the StackOverflow question.

The "empty list" is unfortunate, but it's precisely the indication that the solver failed to produce any models for the very last call. If the model was extracted using with an explicit tuple like this:

```
   try = (extractModels `fmap` allSat (pairCube 1000)) :: IO [(Integer, Integer, Integer)]
```

then we actually get:

```
[(9,27,-6),(0,0,0),(9,27,6),(64,512,24),(1,-1,0),(64,512,-24),*** Exception: SBV.getModel: Cannot construct a model from: SMTModel {modelAssocs = []}
```

which is arguably better.. But since the original-poster asked for `[Integer]`, SBV ended up constructing an empty list, which also makes perfect sense.

Feel free to close this ticket, or elaborate if SBV can do better here!

**Closed** 2015-12-09 00:02 UTC
