### ISSUE TITLE
Significant performence problems with repeated `ite` on `SFunArray`

### ISSUE THREAD

**Issue by ocharles** [LeventErkok/sbv#402] opened 2018-06-29 11:42 UTC
Given the following:

```haskell
module Bug (bug) where

import Prelude hiding ( round )
import Data.SBV
import Data.SBV.Control

bug :: IO ()
bug =
  runSMTWith z3 { verbose = True } $ do
    setLogic Logic_ALL 
    query (loop (mkSFunArray (const false)))

loop :: SFunArray Integer Bool -> Query ()
loop array = do
  i <- freshVar_
  constrain (readArray array i)
  loop (ite (i .== 0) array' array')

  where array' = writeArray array 0 (readArray array 0)
```

I observe that it gets progressively slower and slower. I'm observing this by watching the `sbv` verbose log and noticing that it gets slower and slower to generate `(declare-fun)` for the `freshVar_`. It gets to about 26 declarations then grinds to a halt. Notice that there is no `checkSat` or anything here - the performance problem is squarely in `sbv` generating code to send to `Z3`. This is obviously a nonsensical program - I got to this by taking a much larger program and trimming it down as much as I could.

If you change `loop ( ite ... )` to just `loop array` (which it is equivalent to, both branches are the same) then I don't observe any performance problems (the verbose SBV output scrolls very fast). Also, the `constrain` seems to be necessary. Removing it and adding a bang pattern to `loop` didn't cause the same problem.

GHC: 8.2.2
SBV: 7.9
Z3: 4.6.0

**Comment by ocharles** [comment] 2018-06-29 11:53
Possibly even smaller:

```haskell
module Bug (bug) where

import Prelude hiding ( round )

import Data.SBV
import Data.SBV.Control


bug :: IO ()
bug =
  runSMTWith z3 { verbose = True } $ do
    setLogic Logic_ALL
    query $ do
      i <- freshVar_
      loop i ( mkSFunArray ( const false ) )

loop :: SInteger -> SFunArray Integer Bool -> Query ()
loop i array = do 
  constrain ( readArray array i ) 
  loop i ( ite (i .== ( 0 :: SInteger )) array' array' )

  where array' = writeArray array 0 ( readArray array 0 )
```

Hit "return" in the output and you'll see it gets progressively slower at outputing `(assert)`.

**Comment by ocharles** [comment] 2018-06-29 13:20
I see https://github.com/LeventErkok/sbv/issues/396 uses `SFunArray` too - maybe it's the same bug.

**Comment by LeventErkok** [comment] 2018-06-29 18:57
Merging arrays is always difficult for SBV, as it needs to walk down the chain of updates.  As in #396, I very much suspect that we're losing sharing at some point, only to recover later. But this ends up being extremely costly.

Thanks for the examples, I'll look into them to see if they're the same issue.

**Comment by LeventErkok** [comment] 2018-06-30 04:40
A canonical way to trigger this is:

```haskell
import Data.SBV

f i = proveWith z3{verbose=True} $ do
         bs <- mapM (const free_) [1..i]
         let a :: SFunArray Bool Bool
             a = mkSFunArray (const false)
             b = foldr (\b x -> ite b x x) a bs
         return $ readArray b true .== false
```

As `i` increases `f` takes exponentially more time. The reason is because we lose the sharing during merging of the arrays:

https://github.com/LeventErkok/sbv/blob/master/Data/SBV/Core/Model.hs#L1537

The update gets pushed down the chain of `ite` calls, which is hidden behind a lambda, thus losing sharing and spending exponentially more time recovering it.

Not quite sure how to fix it yet.

**Comment by ocharles** [comment] 2018-06-30 07:43
The good news is I can just use a normal `SArray` and recover performance. I don't know if shared `SFunArrays` would be even faster, but this is fast enough.

**Comment by LeventErkok** [comment] 2018-06-30 17:17
If `SArray` works for you, by all means use them. `SArray`'s map to SMTLib's notion of arrays, that is it requires a solver that understands/supports arrays. The point of `SFunArray` is that you can use it with solvers that don't support arrays (such as abc), as they are completely handled in the Haskell ecosystem, and don't generate any SMTLib code.

Incidentally, as you observed, the issue reported here and #396 is precisely the same and caused by loss of sharing during merging of `SFunArray` values.

**Comment by LeventErkok** [comment] 2018-07-02 09:16
@ocharles 

As of https://github.com/LeventErkok/sbv/commit/77858f34f98bb233b86ed3a9f79f75a3707c9400 SFunArray's should be a lot more performant. There are still some pathetic cases that cause exponential blow-ups, but for regular usage I think they should hold up pretty well.

Note that `mkSFunArray` is removed. Simply use `newArray` to create both regular `SArray`s and `SFunArray`s. (Use a type-signature if necessary to distinguish them.) The "initializer" functionality of `mkSFunArray` is deprecated: If you read a location that was unwritten to before, you will get an uninterpreted constant. This is consistent with how `SArray` works (and how SMT-Lib arrays work in general), and I think the consistency is better from a design perspective. Any program that reads an unwritten cell deserves to be called out!

I'm going to close this ticket since I believe the issue is addressed. However, if you do end up doing some testing and find any issues, please report! Thanks.

**Closed by LeventErkok** 2018-07-02 09:16 UTC
Labels: Performance

**Comment by ocharles** [comment] 2018-07-02 09:23
Wow, that's quite the commit - nice work! While `SArray` works fine, I'll try swapping my `SArray` uses for `SFunArray` and see how it performs. I don't expect anything to get faster, but it'd be interesting to see if there's any type of exponential slow down still present.

**Comment by LeventErkok** [comment] 2018-07-02 15:21
Thanks. There are some inherent difficulties in making SFunArrays as fast as SArrays, but they can pay off as they lead to simpler SMT queries. Please report if you see anything fishy!

**Comment by LeventErkok** [comment] 2018-07-02 21:58
@ocharles Put in a few more optimizations just now; if you've already done a build a refresh might help.
