### ISSUE TITLE
Solver tests on Travis, Tasty for Basic tests

### ISSUE THREAD

**Issue by kanishka-azimi** [LeventErkok/sbv#274] opened 2017-05-30 05:43 UTC
- add makefile target for downloading z3; use the target in Travis builds and run int tests from Travis
- switch Basic tests to use Tasty; create a shared module (e.g. divide SBVIntTest.hs into more TestGroups) for declaring two test groups (basic and int) for each logical section (Basic, CRC, etc)
- add convenience targets in Makefile for skipping slower solver tests - some work done here
- move examples to test-suites to avoid exposing as part of public interface/haddock; link to examples from Readme?
- ~~some convenient, DRY way to discover, name, and allow for deletion of golden files for a given logical section of tests?~~
(Follow-ups from https://github.com/LeventErkok/sbv/issues/212)

**Comment by LeventErkok** [comment] 2017-05-30 07:13
@kanishka-azimi 

Moving to Jenkins would be really nice. And so would running everything using Tasty. But I'll leave it to your judgment to prioritize these, if you ever want to implement any.

All of these are great ideas. I found that "golden" file generation still works (Tasty has an --accept flag), but we have this issue of some of the tests are written in Tasty and some not, which causes a discrepancy. Not a big deal though.

Thanks so much for all the work! And I hope you'll continue to contribute; not just on the test suite but any other part of SBV as well; I'm assuming you're interested in theorem-proving/sat-checking etc. as well.

**Comment by LeventErkok** [comment] 2017-05-30 08:33
I've just added "-j 4" to the test-suite call in the Makefile, and the release time on my 2011 Mac went down to 13 minutes from what used to be ~21 minutes.

That's impressive savings! Thanks!

**Comment by kanishka-azimi** [comment] 2017-05-30 15:14
Cool. I was wondering if any tests might fail with concurrency, but sounds like they are safe.

BTW, if you submit this project Stack or Nix for inclusion, you might need to add back the cabal flag to make int-test-extended not buildable by default, as those projects run `cabal test`. I can help if it unclear what to do, when you reach that point.

Also, the nix build script for this project could reference the solvers executables it depends on.

**Comment by LeventErkok** [comment] 2017-05-30 16:40
Hmm, good point about stackage. It was already there:

    https://www.stackage.org/lts-8.15/package/sbv-5.14

But looks like it's stuck at 5.14 since Cryptol hasn't kept up: https://github.com/fpco/stackage/issues/2251

@acfoltzer @brianhuffman Any chance we can get a newer Cryptol released with a relaxed upper bound on SBV? Why do you guys even limit at <5.15? Is there a problem with later versions? It'd be nice to have stackage track Hackage for sbv releases.

@kanishka-azimi Even if the Cryptol folks relaxed the bound, I think you're right that this'll fail on stackage. So, please go ahead and make the necessary flag changes so we're ready.

For Nix: I'm really ignorant about it. If you feel inclined to do so, I see no reason why we shouldn't. Feel free pursue that; I'd like to be educated on that if you've some pointers to read.

**Comment by kanishka-azimi** [comment] 2017-05-30 16:47
> For Nix: I'm really ignorant about it. If you feel inclined to do so, I see no reason why we shouldn't. Feel free pursue that; I'd like to be educated on that if you've some pointers to read.

Still trying to master it, mostly only read about it. Gabriel wrote an awesome tutorial - https://github.com/Gabriel439/haskell-nix ; It still feels like a moving target.

> Even if the Cryptol folks relaxed the bound, I think you're right that the new test system will fail on stackage. So, please go ahead and make the necessary flag changes so we're ready.

Okay, will try to revisit this pretty soon. I haven't figured out a way to avoid using a flag, but I would like to. I will ask around. Flags end up affecting whether something gets rebuilt, so they might slow down running the two test suites.

**Comment by LeventErkok** [comment] 2017-05-31 05:27
@kanishka-azimi 

[Repeating my code comment]

I've another project that uses tasty, and `--accept` works there.

I think the issue is that we need to use `goldenVsFile` instead of `goldenVsStringShow`. If we start using the file version, I think this problem will go away.

Is there a reason why you haven't used that one?

**Comment by LeventErkok** [comment] 2017-07-03 21:09
@kanishka-azimi I've ported the remaining tests to tasty; without your jump-start this wouldn't have been possible!

There's always room for improvement, but I'll close this ticket and track remaining items separately. Thanks!

**Closed by LeventErkok** 2017-07-03 21:09 UTC
Labels: Nice to have

**Comment by kanishka-azimi** [comment] 2017-07-03 21:11
Great! I have just been really busy with work-related tasks, so this completely fell off my plate.
