### ISSUE TITLE
Timing solver actions in Query produce strange results.

### ISSUE THREAD

**Issue by arrowd** [LeventErkok/sbv#473] opened 2019-06-25 07:31 UTC
In my quest of improving my application performance I used [timeit](http://hackage.haskell.org/package/timeit) package to measure actions inside `Query` monad. It is an instance of `MonadIO`, which made using `timeit` braindead simple. However, I can't explain results I'm getting.

My code:

```
    timeItNamed "Q" $ query $ do
        let getSolution :: Query AlgReal
             getSolution = do
                r <- checkSat
                case r of
                    Sat -> getValue newSik
                    _ -> return 0

             push 1
             sikForT <- timeItNamed "T" $ do
                constrain $ someBigExpression1 newSik .== someConst
                getSolution
             pop 1
             sikForU <- timeItNamed "U" $ do
                constrain $ someBigExpression2 newSik .== someConst
                getSolution
             return $ min sikForU sikForT
```

Running it (in a loop) produce

```
T:   0.13s
U:   0.12s
Q:   0.27s
Solution: 22248.125273155412
T:   0.09s
U:   0.17s
Q:   0.26s
Solution: 12699.338647808143
T:   0.15s
U:   0.17s
Q:   0.32s
...
```

However, it hangs for about 5 secs between `T:   0.13s` and `U:   0.12s`. I tried putting `pop 1` into `timeItNamed` block, but that didn't helped.

I've also changed my problem so that it compute the answer using either "T" or "U" constraint set only and I'm pretty sure that sum of times taken to get separate solutions is visibly less, that when I try to check both constraints in a single query.

Another thing to mention - I had different time results (more realistic, like 5-6 secs) when running `sbv-7.13`, but these were strange in other way.

Maybe I'm just wrong in how I try to measure things?

**Comment by LeventErkok** [comment] 2019-06-25 10:22
I've not used `timeIt` before, so I've no idea how it works or might be used incorrectly/buggy here. But looks like what it's reporting and what you're observing seems to be different.

I'd recommend using the `transcript` options of `runSMT`; like this:

```haskell
runSMTWith z3{transcript = Just "trans.smt2"} $ do 
      x <- free "x"
      constrain (x .>= 2)
      query (io . print =<< checkSat)
```

When finished, this will create a file named `trans.smt2` in the same directory, that will have explicit timing information on how each interaction with the solver took. Furthermore, it's a legitimate `smt2` file: You can pass it to `z3` on the command line and hand-verify of it indeed shows that 5 seconds delay with no involvement from SBV at all.

Do look at that transcript file in detail and try running it outside of Haskell/ghci etc. If the delay is there, then it's the solver taking its time. If not, then SBV is doing something that causes the delay. If latter is the case, I'll have to ask you to come up with something I can run on my own to investigate; or you can do regular GHC based profiling to find out what might be the hold-up.

But the first thing to do is to get SBV completely out of the loop by using the `transcript` feature and make sure the delay isn't caused by the solver. Please report what you find out!

**Comment by LeventErkok** [comment] 2019-06-26 15:15
@arrowd Were you able to make any progress on this? Did `transcript` show any interesting timing problems?

**Comment by arrowd** [comment] 2019-06-26 15:25
Not yet. I hope to make a stab on it this weekend.

**Comment by LeventErkok** [comment] 2019-06-26 15:54
OK. I'm going to close this ticket since there's no SBV actionable item at this time. Feel free to submit a new issue if you suspect SBV is doing something bad.

**Comment by arrowd** [comment] 2019-06-29 15:23
Solver transcript didn't yield any suspicious timings. I ran my program in profiling mode (`+RTS -p`). This, however, made my program run MUCH longer, but I still waited for several hours and get following output:

```
COST CENTRE              MODULE                   SRC                                             %time %alloc

algRealStructuralCompare Data.SBV.Core.AlgReals   Data/SBV/Core/AlgReals.hs:(123,1)-(126,84)       78.3   85.8
```

Is this finding any useful?

**Comment by LeventErkok** [comment] 2019-06-29 16:29
Impossible to say without actually seeing the source program that caused this. 

If you can send me a (hopefully not to big) report that I can compile and run myself, it’ll be really hard for me to understand what’s going on. Would that be possible? A github repo would be the best.

**Comment by arrowd** [comment] 2019-06-29 19:40
I'll try to extract minimal testcase, but that would probably require some work, so I'll resort to it last.

Here are elaborate excerpt from `.prof` file:

```
 progonka.goBeta.bb                Main                       Main.hs:252:37-71                                 22255          0    0.0    0.0    59.7   52.4
  +                                Data.SBV.Core.Model        Data/SBV/Core/Model.hs:1116:3-34                  22256          0    0.0    0.0    59.7   52.4
   svPlus                          Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(146,1)-(149,80)      22257          0    0.0    0.0    59.7   52.4
    liftSym2                       Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1328,1)-(1329,124)   22258          0    0.0    0.0    59.6   52.1
     liftSV2                       Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1316,1)-(1319,34)    22259          0    0.0    0.2    59.6   52.1
      liftSV2.c                    Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1317,9)-(1319,34)    22261    8252688    1.7    0.1    59.5   51.9
       compare                     Data.SBV.Core.Concrete     Data/SBV/Core/Concrete.hs:155:23-25               22625   52374691    0.3    0.0    54.2   50.3
        compare                    Data.SBV.Core.Concrete     Data/SBV/Core/Concrete.hs:(126,3)-(148,76)        22627   52374691    0.3    0.0    53.7   50.3
         algRealStructuralCompare  Data.SBV.Core.AlgReals     Data/SBV/Core/AlgReals.hs:(123,1)-(126,84)        22628   52374691   53.4   50.3    53.4   50.3

progonka.goBeta.bb                 Main                       Main.hs:252:37-71                                 22243          0    0.0    0.0    26.2   27.2
 /                                 Data.SBV.Core.Model        Data/SBV/Core/Model.hs:(1160,3)-(1179,96)         22244          0    0.0    0.0    26.2   27.2
  /.res                            Data.SBV.Core.Model        Data/SBV/Core/Model.hs:1162:14-38                 22245          0    0.0    0.0    26.2   27.2
   svDivide                        Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(176,1)-(178,29)      22246          0    0.0    0.0    26.2   27.2
    liftSym2                       Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1328,1)-(1329,124)   22247          0    0.0    0.0    26.1   27.0
     liftSV2                       Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1316,1)-(1319,34)    22248          0    0.1    0.2    26.1   27.0
      liftSV2.c                    Data.SBV.Core.Operations   Data/SBV/Core/Operations.hs:(1317,9)-(1319,34)    22250    8252688    1.4    0.1    25.9   26.8
       compare                     Data.SBV.Core.Concrete     Data/SBV/Core/Concrete.hs:155:23-25               22689   52692405    0.3    0.0    20.8   25.4
        compare                    Data.SBV.Core.Concrete     Data/SBV/Core/Concrete.hs:(126,3)-(148,76)        22691   52692405    0.3    0.0    20.3   25.4
         algRealStructuralCompare  Data.SBV.Core.AlgReals     Data/SBV/Core/AlgReals.hs:(123,1)-(126,84)        22692   52692405   19.9   25.4    19.9   25.4
```

and the corresponding code:

```
goBeta (a:alpha) (f:fj) b = let bb = ((aj * b + f) / (cj - aj * a)) in
                                    bb : goBeta alpha fj bb
```

If that doesn't help, I'll get to producing a minified testcase.

**Comment by LeventErkok** [comment] 2019-06-29 20:41
No, it doesn't really help. Really need to see something that I can run myself.

**Comment by LeventErkok** [comment] 2019-07-08 17:05
@arrowd Any progress on this? I'm planning to make a release later this week so would be good to incorporate any changes we might make.

**Comment by arrowd** [comment] 2019-07-08 17:06
I've invested a lot of time into it and wasn't able to create a minified reproducer.

I plan to refactor my code and then try again. Feel free to close this, meanwhile.

**Comment by LeventErkok** [comment] 2019-07-08 17:11
OK, feel free to reach out if you spot if SBV is doing something funky.

**Closed by LeventErkok** 2019-07-08 17:11 UTC
Labels: Need more info
