### ISSUE TITLE
Building arrays outside of `Symbolic` or `Query` contexts

### ISSUE THREAD

**Issue by MrChico** [LeventErkok/sbv#553] opened 2020-08-11 13:03 UTC
The treatment of Symbolic Arrays is quite different from the other supported symbolic types of SBV.
They cannot have a `literal` component, and cannot appear in negative position of type signatures unless
we are in the `Symbolic` or `Query` monadic contexts where we can create them using `newArray`.

This forces us developers to define functions that deal with arrays in the global context, complicating development.
For example, it is impossible to write the function:
```
fromList :: [(SInteger, SInteger)] -> SArray SInteger SInteger
```
We must instead write:
```
mFromList :: [(SInteger, SInteger)] -> Query (SArray SInteger SInteger)
mFromList entries = do
   a <- newArray_ (Just 0)
   uncurry (writeArray a) <$> entries
```
Or, if we want to avoid the Query context, keep some global state of uninitialized arrays around:
```
insertInto :: SArray SInteger SInteger -> [(SInteger, SInteger)] -> SArray SInteger SInteger
insertInto entries = uncurry (writeArray a) <$> entries
```

Would it be possible to allow the creation of arrays outside of monadic contexts? For example, given
```
constantArray :: b -> SArray a b
```
one could define
```
fromList :: [(SInteger, SInteger)] -> SArray SInteger SInteger
fromList entries = uncurry (writeArray (constantArray 0)) <$> entries
```

**Comment by LeventErkok** [comment] 2020-08-11 17:21
I'm not sure if I follow. Side note: What do you mean by `uncurry entries` in your code snippets? `uncurry` takes a function, but you're passing lists. Does your `mFromList` function type check?

In general, array creation has to happen in a monadic context. (Either `Symbolic` or `Query`.) There's no way to create an array without being in one of those contexts. I don't see an easy way to work around that.

If you can post a simple example of what you'd like to be able to write and what you have to write (latter actually type checking!) that'd help.

**Comment by MrChico** [comment] 2020-08-11 17:48
> I'm not sure if I follow. Side note: What do you mean by `uncurry entries` in your code snippets? `uncurry` takes a function, but you're passing lists. Does your `mFromList` function type check?

Oops. I did not typecheck this. I'm writing a hypothetical function directly in the issue here. May still be some minor issues with it, but hopefully the point comes across.

> In general, array creation has to happen in a monadic context. (Either `Symbolic` or `Query`.) There's no way to create an array without being in one of those contexts. I don't see an easy way to work around that.
> 
> If you can post a simple example of what you'd like to be able to write and what you have to write (latter actually type checking!) that'd help.

Perhaps this better illustrates the need for the hypothetical `fromList` above: imagine we are dealing with a list of symbolic values which we either access through symbolic indices, or at concrete locations. In the former case, we would use `SArray`, while in the latter it suffices to use `[SInteger]`.

Of course we can use `SArray` for both, but I'm imagining that the list will be more performant if we do a lot of writes and reads to known locations 

We would have the type:
```
data Buffer b = Dynamic (SArray Integer b) | Static [b]
```

Now imagine we want to define a monoid instance for this type.
We would want to convert a list into an smt array, probably with a function like the hypothetical `fromList` from above. We won't be able to use the monadic variant here.

**Comment by MrChico** [comment] 2020-08-11 17:53
I can understand if there is no easy way to do this, I can find other workarounds. I just wanted to see if you had any thoughts here

**Comment by LeventErkok** [comment] 2020-08-11 19:10
I see.. I suppose something like `fromList` is reasonable, but I'm not sure if it would be possible to have that return a non-Query/Symbolic value. Let me think about this for a bit.

**Comment by LeventErkok** [comment] 2020-08-12 01:24
@MrChico 

I've just pushed some changes, adding `sListArray`. Can you give it a try and see if it fits your needs?

Here's an example use:

```haskell
module T where

import Data.SBV

a :: SArray Integer Integer
a = sListArray (Just 7) [(1, 12), (2, 5) , (3, 6), (75, 5)]

p :: IO SatResult
p = sat $ do i <- sInteger "i"
             j <- sInteger "j"

             constrain $ i ./= j
             constrain $ i `sElem` [1, 2, 3, 75]
             pure $ readArray a i .== readArray a j
```

When I run this, I get:

```
*T> p
Satisfiable. Model:
  i =  2 :: Integer
  j = 75 :: Integer
```

**Comment by MrChico** [comment] 2020-08-12 08:55
Amazing! Will try it out!

**Comment by MrChico** [comment] 2020-08-14 17:27
Hmm, there are some interesting things going on here.

This query succeeds:
```
constArr :: Query ()
constArr = let a, b :: SArray Integer Integer
               a = sListArray Nothing []
               b = sListArray Nothing []

           in do -- the arrays can be distinct
                 constrain $ readArray a 0 ./= readArray b 0
                 ensureSat
```
while this one fails:
```
constArr :: Query ()
constArr = let a, b :: SArray Integer Integer
               mkArray = sListArray Nothing []
               a = mkArray
               b = mkArray

           in do -- the arrays are always equal
                 constrain $ readArray a 0 ./= readArray b 0
                 ensureSat
```
which is a little confusing.

It almost seems like we are breaking some fundamental functional aspect of Haskell here... 
I'm not quite sure what to make of this. 

In a way, I can imagine how this might occur; in the second variant we are calling the same function twice, so of course it should have the same result... But then again, the same is true for the first variant, only we have not given this function a name. 

What do you make of this curiosity? Is it bad news for `sListArray` and this approach in general? It definitely caused my code to behave in unexpected ways; all of my arrays had been truncated into one!

**Comment by LeventErkok** [comment] 2020-08-14 18:09
@MrChico Yeah, that doesn't look good. I'll have to take a look. If this is unavoidable, I would be against adding `sListArray`.

**Comment by LeventErkok** [comment] 2020-08-14 19:12
The problem is with the initializers. In the first case, different calls get different initializers. In the second case, they get the same initializer.

There's really no good way to solve this; except for insisting on an initializer. That would fix the issue. (i.e., `sListArray` would always have to receive the first argument to say what the uninitalized read-value is.)

Would that work for you?

**Comment by LeventErkok** [comment] 2020-08-14 19:15
Of course, you can always pass an uninterpreted value as the initializer. That way you still control the unread-value. So, this isn't really a loss of functionality, just not as nice.

**Comment by MrChico** [comment] 2020-08-14 19:33
Yes, I think I can make things work with a given initializer

**Comment by LeventErkok** [comment] 2020-08-18 02:43
@MrChico Looking at this further, I'm not quite sure if even requesting the initializer is enough. Because one can always pass `uninterpret "unint"` as an argument and have exactly the same problem. 

I pushed in a new version. Can you do an experiment and see if it works? I'm pretty sure it'll fail if you pass `uninterpret "val"` as the initializer, bit passing constant like `3` etc. might work. I'd like to know what you find out.

**Comment by LeventErkok** [comment] 2020-08-18 06:32
@MrChico I've changed the type to:

```
sListArray :: (HasKind a, SymVal b) => b -> [(SBV a, SBV b)] -> array a b
```

Note that the first argument is now `b`, not `SBV b`. This avoids the issue with symbolic initializers, as the value here has to be completely concrete and cannot be skipped.

I think this should address the issue regarding initialization order. Can you give this a try?

**Comment by MrChico** [comment] 2020-08-18 11:53
@LeventErkok Tried it and it works well for my needs!

**Comment by LeventErkok** [comment] 2020-08-18 14:30
Great. I'm closing this issue; feel free to file a new one as needed.

**Closed by LeventErkok** 2020-08-18 14:30 UTC
Labels: New feature
