### ISSUE TITLE
Results variables rotated around in data structure returned by allSat

### ISSUE THREAD

**Issue by habbler** [LeventErkok/sbv#102] opened 2015-01-07 17:59 UTC
The SMT results are not mapped to their correct positions in the resulting Haskell data structure in the following example:

(Hacked version of Data.SBV.Examples.Puzzles.MagicSquare containing tuples)

module SBV_Magic_Bug where

import Data.SBV
import Control.Applicative
import Control.Monad (when)

type Direction = SWord8

type Colour = SWord8

type Elem = (Direction, Colour)

type Row = [Elem]

type Board = [Row]

check :: [Elem] -> SBool
check = bAll $ \(dir,color) -> dir .>= 0 &&& dir .<= 3 &&& color .== 9

type Coord = (Int, Int)

isMagic :: Board -> SBool
isMagic rows = (bAnd $ map checkRow items) &&& (row1 $ head rows) &&& (rowN $ last rows) 
  where items = rows
        checkRow row = (rowCol1 $ head row) &&& (check row) &&& (rowColn $ last row)
        row1 = bAll $ \(dir,color) -> dir ./= 0
        rowN = bAll $ \(dir,color) -> dir ./= 2
        rowCol1 (dir,color) = dir ./= 3
        rowColn (dir,color) = dir ./= 1

-- | Group a list of elements in the sublists of length @i@
chunk :: Int -> [a] -> [[a]]
chunk _ [] = []
chunk i xs = let (f, r) = splitAt i xs in f : chunk i r

test1 :: Symbolic [(SWord8,SWord8)]
test1 =  mapM (const ((,) <$> exists_ <*> exists_)) [1..10]

existsPairN n = mapM (const ((,) <$> exists_ <*> exists_)) [1..n]

existsPairN_fail n = zip <$> mkExistVars n <*> mkExistVars n

-- | Given @n@, magic @n@ prints all solutions to the @nxn@ magic square problem
cover :: Int -> IO ()
cover n
 | n < 0 = putStrLn $ "n must be non-negative, received: " ++ show n
 | True  = do putStrLn $ "Finding all " ++ show n ++ "-magic squares.."
              res <- allSat $ (isMagic . chunk n) <$> existsPairN_fail n2 
              cnt <- displayModels disp res
              putStrLn $ "Found: " ++ show cnt ++ " solution(s)."
   where n2 = n * n
         disp i (_, model)
          | lmod /= n2
          = error $ "Impossible! Backend solver returned " ++ show n ++ " values, was expecting: " ++ show lmod
          | True
          = do when (i > 10) $ error "...More"
               putStrLn $ "Solution #" ++ show i
               mapM_ printRow board
               putStrLn $ "Valid Check: " ++ show (isMagic sboard)
               putStrLn "Done."
          where lmod  = length model
                board = chunk n model
                sboard = map (map (\(x,y) -> (literal x, literal y))) board
                sh2 z = let s = show z in if length s < 2 then ' ':s else s
                printRow r = putStr "   " >> mapM_ (\x -> putStr (sh2 x ++ " ")) r >> putStrLn ""
================= End of module =============
Prelude SBV_Magic_Bug> cover 2
Finding all 2-magic squares..
Solution #1
   (2,3) (1,0) 
   (9,9) (9,9) 
Valid Check: False
Done.

Replacing the function call existsPairN_fail with existsPairN results in correct solutions. i.e. the order the variables are created in makes a difference!

Finding all 2-magic squares..
Solution #1
   (2,9) (3,9) 
   (1,9) (0,9) 
Valid Check: True
Done.

**Comment by habbler** [comment] 2015-01-07 18:03
http://lpaste.net/118011

**Comment by LeventErkok** [comment] 2015-01-08 05:45
This is not a bug.

When you call `displayModels`, SBV will provide the model variables in the order you create. So, if you create them in different orders, then it will be passed to the `displayModels` function in that particular order that you created. Therefore, when you have the line:

   `board = chunk n model`

You are getting the variables in order of creation to that board. With `existsPairN`; the `chunk` function does the right thing. But with `existsPairN_fail`; the `chunk` function does something completely different; i.e., it constructs the board incorrectly.

Put another way, the order you allocate directly corresponds to the model you will receive, and thus any code you write that uses that model will have to respect that order. To fix this issue, if you use `eistsPairN_fail` then you should also change the construction of the board accordingly when you reconstruct the board.

Here's a simple example that might help you:

```
t1 = sat $ (sWord8 "a" >> sWord8 "b" >> sWord8 "c" >> sWord8 "d" >> return (true :: SBool))
t2 = sat $ (sWord8 "a" >> sWord8 "c" >> sWord8 "b" >> sWord8 "d" >> return (true :: SBool))
```

If you run `t1` and `t2`; you'll get:

```
*Main> t1
Satisfiable. Model:
  a = 0 :: SWord8
  b = 0 :: SWord8
  c = 0 :: SWord8
  d = 0 :: SWord8
*Main> t2
Satisfiable. Model:
  a = 0 :: SWord8
  c = 0 :: SWord8
  b = 0 :: SWord8
  d = 0 :: SWord8
```

Note how the order is preserved as you created them.. (`exists` and `sWord8` are essentially the same function, latter is just type-specialized for `Word8`). And this order is also preserved when the `disp` function is called as in your example. Thus, you have to construct the board accordingly.

I hope that's clear. As a rule of thumb, always keep in mind that the order you create the variables, and the order you receive them in a model will be in one-to-one correspondence, and thus you have to interpret the values correctly when you display the model.

**Closed by LeventErkok** 2015-01-08 05:45 UTC
