### ISSUE TITLE
CVC4 solver config adds model-witness-value flag

### ISSUE THREAD

**Issue by Torrencem** [LeventErkok/sbv#618] opened 2022-03-22 19:39 UTC
When I run the default CVC4 SMTConfig, I get
```
*** Data.SBV: fd:82: hGetLine: end of file:
***
***    Sent      : (set-option :print-success true)
***
***    Executable: /usr/bin/cvc4
***    Options   : --lang smt --incremental --interactive --no-interactive-prompt --model-witness-value
***
***    Hint      : Solver process prematurely ended communication.
***                It is likely it was terminated because of a seg-fault.
***                Run with 'transcript=Just "bad.smt2"' option, and feed
***                the generated "bad.smt2" file directly to the solver
***                outside of SBV for further information.
```
Upon further investigation, this is because my cvc4 installation doesn't have an option `--model-witness-value`. Removing this option, I then get

```
*** Data.SBV: Failed to initiate contact with the solver!
***
***   Sent    : (set-option :print-success true)
***   Expected: success
***   Received: (set-option :print-success true)
***
*** Try running in debug mode for further information.
```

which leads me to believe something strange is weird about my cvc4 installation (I installed using `sudo apt-get install cvc4` on ubuntu). Note that this second error message is especially strange:

```
$ cvc4 --lang smt --incremental --interactive --no-interactive-prompt
(set-option :print-success true)
success
...
```
So I can't figure out why SBV is reporting differently...

**Comment by Torrencem** [comment] 2022-03-22 19:40
Note, on my installation
```
cvc4 --help | grep "\--model-witness-value"
```
gives nothing

**Comment by Torrencem** [comment] 2022-03-22 19:46
I should clarify, this happens when I call
```
satWith cvc4 mypredicate
```
and similar experiments were done with
```
satWith (cvc4{verbose=True,solver=(solver cvc4){options=const ["--lang", "smt", "--incremental", "--interactive", "--no-interactive-prompt"]}}) mypredicate
```
on commit 60b97d83aa29612f8317ddf40c5f310f3eb536e5

**Comment by LeventErkok** [comment] 2022-03-23 00:31
I stopped tracking CVC4; unless you’re using the exact version listed in https://github.com/LeventErkok/sbv/blob/69f3eba6ca03afe4695ebee0229999c0c22f8445/SMTSolverVersions.md?plain=1#L14, there might be version difference issues. 

In particular, your second problem is a duplicate of #615.

As I indicated there, supporting arbitrary versions of CVC4 is not worth effort. All CVC4 users should move to CVC5 (https://cvc5.github.io/), which is supported by SBV. Since CVC4 is now superseded by CVC5, there’s no reason for SBV to keep it in the portfolio, and indeed I plan to remove support for it sometime this year. 

Is there a particular reason why you need CVC4? If so, try to get the exact version listed in the SMTSolverVersions.md file. If not, please move to CVC5. Let me know if neither of these options is possible for you.

**Comment by Torrencem** [comment] 2022-03-23 11:50
Unfortunately, it seems for some reason CVC5 doesn't support regexes (at least my error messages seem to indicate this), but I'll try installing the exact version of CVC4

**Comment by Torrencem** [comment] 2022-03-23 12:14
Yeah, it looks like support for string / regexp theory was really fleshed out in CVC4 1.8 (see the changelog here: https://github.com/cvc5/cvc5/releases) which we're making use of, and the version this was tested for is much older than that. I'm not sure when these features will be added to CVC5, which puts this in a weird spot

**Comment by LeventErkok** [comment] 2022-03-23 12:17
So far as I know CVC5 is a superset of CVC4. You might have to pass some extra arguments though, check their command line options, things that start with `—string`, something like `—string-exp` might work. 

You can use https://hackage.haskell.org/package/sbv-8.17/docs/Data-SBV.html#v:extraArgs to send those arms to CVC5 easily.

**Comment by Torrencem** [comment] 2022-03-23 12:23
I found it out, it's a naming issue. CVC5 doesn't support the old regexp names like `str.to.re` and instead only expects `str.to_re`. In addition, CVC5 doesn't like when you append only one string (i.e. `(re.++ (str.to_re "z"))`, which I got in the output of SBV

**Comment by Torrencem** [comment] 2022-03-23 12:24
(when I try the only-one-string appended, I get
```
(error "Parse Error: <stdin>:2.60: Invalid kind 'REGEXP_CONCAT', expected Terms with kind REGEXP_CONCAT must have at least 2 children and at most 67108863 children (the one under construction has 1)")
```). So there might need to be some adjusting of the output of SBV to support this

**Comment by Torrencem** [comment] 2022-03-23 12:25
I should mention
```
$ cvc5 --version
This is cvc5 version 0.0.6-dev.61.cd91ef90e [git cd91ef90e on branch master]
compiled with GCC version 9.3.0
on Jan 21 2022 10:03:00
```

**Comment by Torrencem** [comment] 2022-03-23 12:27
Note this is a change in CVC4 1.8 (see the changelog I linked earlier) to support the new names. I guess in CVC5 or in 1.8 they dropped support for the old names

**Comment by LeventErkok** [comment] 2022-03-23 12:35
I’m traveling this week, so this’ll have to wait till I get back to a suitable computer. 

Adjusting output based on solver support is a tricky game, we should produce SMT-lib compliant output and file tickets with z3/CVC5 etc to have them support the sanctioned versions. I suspect it might be z3 that’s not playing by the rules, and I was probably not careful and just following its lead. 

If you can find out what the official output should be, and file corresponding tickets for z3/CVC5 to follow suit, that’d be great. And then we can patch sbv to do the same.

**Comment by Torrencem** [comment] 2022-03-23 12:56
In the meantime,
https://github.com/Torrencem/sbv/commit/146974d3f4552bb7cd09f837506ed74fdf9a879b
and 
https://github.com/Torrencem/sbv/commit/af9da8b36a6ca1cd3ef14ffc216d080d05494107
solve my problems in the short term. I'll try to research more what's going on with `str.in.re` vs `str.in_re` and why cvc5 seems to support only one while z3 seems to support only the other. (By the way, testing this, z3 doesn't support `str.in_re`. Very odd)

**Comment by LeventErkok** [comment] 2022-03-23 13:47
Please file a ticket with z3 github, they should support what SMTLib stipulates. (Which I believe is what CVC5 ıs doing, but would be good to double check.)

**Comment by Torrencem** [comment] 2022-03-23 14:37
Made an issue
https://github.com/Z3Prover/z3/issues/5919

**Comment by LeventErkok** [comment] 2022-03-23 22:17
Yeah, always use latest z3! (Like compile out of GitHub master)

**Comment by LeventErkok** [comment] 2022-03-27 22:42
Seems to me like there's no actionable item for SBV on this ticket; moving to CVC5 and using the latest version of z3 is the way to go.

Feel free to re-open if the issue still persists after you move to latest versions of CVC5 and z3.

**Closed by LeventErkok** 2022-03-27 22:42 UTC

**Comment by d-xo** [comment] 2022-06-20 15:36
I am running into the same issue with cvc5. I call cvc5 with `runSMTWith cvc5{SBV.verbose=smtdebug}`, and I see the following error when I try to use it:

```
*** Data.SBV: fd:42: hGetLine: end of file:
***
***    Sent      : (set-option :print-success true)
***
***    Executable: /nix/store/g7ww0wm4qz1m6818lylcdzq8l4zrkppd-cvc5-1.0.0/bin/cvc5
***    Options   : --lang smt --incremental --no-interactive --model-witness-value
***
***    Hint      : Solver process prematurely ended communication.
***                It is likely it was terminated because of a seg-fault.
***                Run with 'transcript=Just "bad.smt2"' option, and feed
***                the generated "bad.smt2" file directly to the solver
***                outside of SBV for further information.
```

If I call `cvc5` with the same options directly I get the following error:

```
< cvc5 --lang smt --incremental --no-interactive --model-witness-value
(error "Error in option parsing: can't understand option `--model-witness-value'")

Please use --help to get help on command-line options.
```

I am using cvc5 1.0.0 from nixpkgs 22.05 ([package definition](https://github.com/NixOS/nixpkgs/blob/d17a56d90ecbd1b8fc908d49598fb854ef188461/pkgs/applications/science/logic/cvc5/default.nix)).

**Comment by LeventErkok** [comment] 2022-06-20 20:35
@d-xo Looks like they dropped this flag from the newer releases. I need to do some investigation and figure out what to replace it with. Alas, this won't happen for a few weeks.

In the mean-time, I'm tracking this in #626, and it lists a workaround, by using the environment variable `SBV_CVC5_OPTIONS`. It works for me; see if it helps you. If not please comment on that ticket.
